### ISSUE TITLE
Some videos are not listed by the add-on & Videos listed in all categories are the same

### ISSUE THREAD

**Issue by albinou** [known-as-bmf/plugin.video.arteplussept#31]
Hi,
I noticed 2 issues that I think are related:
* the following video is not listed by the add-on: http://www.arte.tv/guide/fr/065307-001-A/cancer-une-biographie-1-2
* When listing videos in categories, the result is the same for all categories

Thanks to tcpdump, I observed that Kodi fetches these 2 URLs for the 2 different categories:
* http://www.arte.tv/papi/tvguide/videos/plus7/program/F/L2/arts-spectacles-classiques/ALL/-1/AIRDATE_DESC/0/0/DE_FR/.json
* http://www.arte.tv/papi/tvguide/videos/plus7/program/F/L2/cinema/ALL/-1/AIRDATE_DESC/0/0/DE_FR/.json

And these 2 URLs gives the JSON same content.

I wanted to check what the API looks like but I can' t find any documentation on it. Do you where I can get some?

Thanks for your help and this nice plugin :)

**Comment by albinou** [comment]
Oh, if needed, I am using Kodi 15.2 on an OpenElec 6.0.3.

**Comment by known-as-bmf** [comment]
Is this issue still ongoing ?

**Comment by mishka81** [comment]
Yes, the problem is still present.

Ex : https://www.arte.tv/fr/videos/087078-003-A/de-shining-a-2001-l-odyssee-de-l-espace-par-l-orchestre-philharmonique-de-radio-france/

Not visible in "ARTE Concert/Classique"

**Comment by thomas-ernest** [comment]
I could search for "orchestre philarmonique de radio france" from the latest version of the plugin and find the below content.
<img width="960" alt="image" src="https://github.com/known-as-bmf/plugin.video.arteplussept/assets/479923/8260af81-072d-479e-9458-785ba01bcb01">
Did the same search on the website and it is consistent except the order :
<img width="960" alt="image" src="https://github.com/known-as-bmf/plugin.video.arteplussept/assets/479923/6780744f-3408-49af-ba5f-eda5e217d22d">
Note: website "Kent Nagano" = plugin "Féstival présence 2023".

The one shared by @mishka81 is not available Arte website though.

There is no more display of unreferenced content anymore. The addon behavior is consistent with Arte Website behavior. You might be unable to access content that is part of your history or favorites, if Arte changed the availability of their content. Not because of the plugin anymore, since latest version built from https://github.com/thomas-ernest/plugin.video.arteplussept/

Please reopen the ticket with a new example based on the latest version of the plugin if needed.
