### ISSUE TITLE
Can't find all episodes of a long series

### ISSUE THREAD

**Issue by lkomsa** [known-as-bmf/plugin.video.arteplussept#70]
I'm watching the serie "The killing" which have 3 seasons. The first have 20 episodes, the others 10.
When I open the folder "The Killing", I have 12 episodes for the first seasons, 10 for the second and 10 for the last one.
So I don't know how to reach episodes 13, 14... 20 of the first season. They are however avaible on the Arte site or with the application CaptyTV.

Is it a limitation of the Arte API ?

For information, on my TV Panasonic, I have another application Arte+7 (quite poor and so slow). When I access the screen of "The Killing", I have three lines for each season. The first one show only 12 episodes. The only way to reach the episode 13 is to launch the twelfth and to look at the suggestion which contains the next one...

Thank you.
Lionel

**Comment by known-as-bmf** [comment]
Hello and thank you for your feedback.

The API endpoint used to retrieve the episodes for this show is this one: http://www.arte.tv/hbbtvv2/services/web/index.php/EMAC/teasers/collection/v2/RC-019568/fr (you can use `/de` instead of `/fr` at the end if you prefer German).

For season 1 (`subCollections[0]`), only 12 videos are returned.

It says that there is a second page (`subCollections[0].nextPage` is `1`) but I have no idea how to access it.

From my investigation it should be something like http://www.arte.tv/hbbtvv2/services/web/index.php/EMAC/teasers/collection/v2/RC-019568/page/2/fr but nothing is returned. 

As you mentioned, there is a "recommendation" endpoint that returns the 13th episode when queried with the 12th episode but I don't see how it could be integrated in the plugin.

http://www.arte.tv/hbbtvv2/services/web/index.php/OPA/v3/videos/recommendations/040374-012-A/6/fr/ALL,DE_FR,EUR_DE_FR,SAT

**Comment by lkomsa** [comment]
Thank you for your answer. It's very interesting and almost fun to search for the right url. I am a developper too and I know a little about web services ;)

For the url for page 2, it would be more logic something like:  http://www.arte.tv/hbbtvv2/services/web/index.php/EMAC/teasers/collection/v2/RC-019568/subcollections/0/page/1/fr
Because it's the subcollection 0 which have 2 pages, not the collection... But I'm sure you alreday try this...

How did you get all the information about the URLs you already know? Is there an API description somewhere?

**Comment by known-as-bmf** [comment]
You can find pretty much everything while browsing http://www.arte.tv/hbbtvv2/ and inspecting network.

**Comment by thomas-ernest** [comment]
Support for pagination being introduced wih https://github.com/thomas-ernest/plugin.video.arteplussept/pull/21
for a future version of the plugin (expected for 1.4.0).

**Comment by thomas-ernest** [comment]
Version 1.4.0 released with pagination support in search results, collections, history and favorites.
