### ISSUE TITLE
Liste semaine : error

### ISSUE THREAD

**Issue by Rvhalewyn** [known-as-bmf/plugin.video.arteplussept#75]
For at least 2 days now, I've got an error message trying to open the very useful list, Semaine. [Screen prints of error ](https://www.dropbox.com/sh/r0fefj30yz0vh3b/AABP7xKsLV6yNNq8VoQiqLlEa?dl=0)

**Comment by known-as-bmf** [comment]
I will look into it when I have the time. Probably an arte api change again, sorry for the inconvenience.

**Comment by known-as-bmf** [comment]
Après avoir regardé très brièvement, rien ne semble avoir changé pour ces points d'api, mais certains jours retournent une erreur HTTP 500...

Je vais essayer de travailler sur un contournement d'ici la fin de la semaine prochaine.

J'ai aussi vu que les catégories / menus sont tout cassés, j'y jetterai un coup d'œil aussi.

**Comment by WalterPepeka** [comment]
Arte semble (à nouveau) avoir modifié son arborescence : dans de nouveaux menus (Les Incontournables, Dans mon assiette...) apparaissent systématiquement un seul répertoire Video Listing (MOST_VIEWED)

**Comment by known-as-bmf** [comment]
Il semblerait qu'Arte soit en plein remaniement de leurs APIs (DTOs & structure changée, catégories vides, catégories pointant faussement vers MOST_VIEWED...), même l'application hbbtv (http://www.arte.tv/hbbtvv2/) est à la ramasse.


Je ne sais pas trop quoi faire, soit attendre un peu la stabilité, soit essayer de bricoler un fix qui sera probablement bientôt obsolète.

**Comment by Rvhalewyn** [comment]
Dommage.
Heureusement il y toujours Arte7 app pour portable + chromecast en attendant ...

**Comment by known-as-bmf** [comment]
Je vais au moins créer un fix #76 pour l'erreur originelle.

Je vais créer un nouveau ticket pour les points d'API qui changent.

**Comment by thomas-ernest** [comment]
There is no more menu list Semaine neither API collection MOST_VIEWED since the partial integration of Arte TV API (Same as on the web site).
There is no more display of unreferenced content. The addon behavior is consistent with Aret Website behavior. You might be unable to access content that is part of your history or favorites, if Arte changed the availability of their content. Not because of the plugin anymore, since latest version built from https://github.com/thomas-ernest/plugin.video.arteplussept/
