### ISSUE TITLE
Video seen on art.tv not visible from the addon

### ISSUE THREAD

**Issue by cavepopo** [known-as-bmf/plugin.video.arteplussept#78]
Hi,

Fist thank you for bringing arte to kodi, it is great.

There are some videos that I can't find using the addon (https://www.arte.tv/fr/videos/078196-000-A/histoire-du-trafic-de-drogue-1-3/ and this one : https://www.arte.tv/fr/videos/RC-021275/l-effet-domino/ for example).

I tried searching everywhere but could not find'em, any ideas ?

Thanks again for your valuable work

**Comment by wcndave** [comment]
Wow, I came here again, because I was looking for the exact same video (albeit in german), https://www.arte.tv/de/videos/078196-000-A/der-grosse-rausch-1-3/

And I can't find it anywhere... Have spent more time looking through the lists than it would be to go to a PC and watch it!

I tried the Semaine category which shows all by date, however it only goes back about a week.

I am not sure this is a github issue, however it would be great to be able to find what you're looking for!

**Comment by wcndave** [comment]
> Hi,
> 
> Fist thank you for bringing arte to kodi, it is great.
> 
> There are some videos that I can't find using the addon (https://www.arte.tv/fr/videos/078196-000-A/histoire-du-trafic-de-drogue-1-3/ and this one : https://www.arte.tv/fr/videos/RC-021275/l-effet-domino/ for example).
> 
> I tried searching everywhere but could not find'em, any ideas ?
> 
> Thanks again for your valuable work

Another way to do this, is to manually add to favourites.  It does require a reboot for the fav file to take effect as it's now in memory, however you just get the show ID from the URL like you have above and add new lines to favs

`Pi4-LE-2:~/.kodi # more userdata/favourites.xml
<favourites>
    <favourite name="Der Grosse Rausch 1/3" thumb="http://api-cdn.arte.tv/api/mami/v1/program/de/078196-000-A/300x170?ts=1633355249">PlayMedia(&quot;plugin://plugin.video.arteplussept/play/SHOW/078196-000-A&quot;)</favourite>
    <favourite name="Der Grosse Rausch 2/3" thumb="http://api-cdn.arte.tv/api/mami/v1/program/de/078197-000-A/300x170?ts=1633355249">PlayMedia(&quot;plugin://plugin.video.arteplussept/play/SHOW/07817-000-A&quot;)</favourite>
    <favourite name="Der Grosse Rausch 3/3" thumb="http://api-cdn.arte.tv/api/mami/v1/program/de/078198-000-A/300x170?ts=1633355249">PlayMedia(&quot;plugin://plugin.video.arteplussept/play/SHOW/078198-000-A&quot;)</favourite>
</favourites>
`

I changed both the thumb URL and the play URL and it works fine.  

And yes, the &quot; above is how it really is in the file.

**Comment by florentk** [comment]
related to #77

**Comment by thomas-ernest** [comment]
Hello,

@known-as-bmf and contributors thank you for the addon.
@wcndave I got the same idea as you. Instead of manually adding favorites, I was thinking at reusing arte.tv api favorites.

The concept of user account exists in arte.tv (website and mobile app). The user can bookmark his/her favorite videos. It is possible to get user favorite from arte.tv API (https://api.arte.tv/api/emac/v3/) with 2 requests : login + favorites.

Please share your thoughs about the below solution 
- 2 new settings to store usename (text) and password (hidden text) for authentication
- when displaying the main menu,
  - checking if a user is configured, otherwise don't do anything. if incomplete settings (user without password and vice versa, error notification)
  - try to authenticate, if it fails display an error notification
  - fetch user favorites and display a categories / menu-item favorites
  - if there is no favorite the category is empty, otherwise favorite videos are listed.

Note : Likewise, the "last seen" category can be supported.

**Comment by thomas-ernest** [comment]
Hello @cavepopo 
I fixed this issue in latest version in my fork (currently [v1.1.5](https://github.com/thomas-ernest/plugin.video.arteplussept)).
Can you kindly try it and close this issue ?
Thank you

**Comment by cavepopo** [comment]
Hi,

I'll try to find some time to test this, thanks for your effort !

**Comment by thomas-ernest** [comment]
Hello @cavepopo,

I assume your tests were successful. Feel free to re-open the issue with new traces, if you want me to have a look.

Thank you,
Best regards,
