### ISSUE TITLE
no series returned for ALL endpoint

### ISSUE THREAD

**Issue by clesauln** [known-as-bmf/plugin.video.arteplussept#79]
Hello,
I want to list Series but result are limited, only some categories return videos.
The API seems to return no results for ALL Category for exemple : 
https://www.arte.tv/hbbtvv2/services/web/EMAC/teasers/category/v2/SER/fr

Is the there a way to get all videos ordered by title ?
Thanks for your work

**Comment by thomas-ernest** [comment]
Hello @clesauln ,

Now, in versions 1.1.5+, content is ordered almost like in Arte TV API reply. The need to re-order items is less critical.

I couldn't find a way to order items in menu from Kodi interface. I think it is a prefered solution, because this need is not limited to this plugin.

Is it ok to close this usse please ?

Thank you

**Comment by clesauln** [comment]
OK,
You can close it, the issue is more related of how content is dispatcher
from Arte tv API.

Le dim. 6 août 2023, 16:52, Thomas ERNEST ***@***.***> a
écrit :
